package com.fabio.CRUD.negocio.usuario;

public enum CodigoErroDTO {
	EMAIL_JA_CADASTRADO, CAMPO_NULO, NENHUM_USUARIO_CADASTRADO, USUARIO_NAO_ENCONTRADO, ERRO_AO_LER_ARQUIVO,
	ERRO_AO_SALVAR_ARQUIVO, FORMATO_EMAIL_ERRADO, TAMANHO_DE_NOME_INVALIDO, TAMANHO_DE_SENHA_INVALIDO, SUCESSO,
	SENHA_DIFERENTE, ACESSO_INVALIDO;
}
